export type Order = {
  id: string;
  appointment_date: string;
  appointment_hour: string | null;
  appointment_local: string | null;
  customer: string;
  customer_id: string;
  phone: string;
  amount: number;
  products: string;
  delivery_status: "Entregar" | "Coletar" | "Coletado";
  payment_status: "Unpaid" | "Paid";
  payment_method: "Dinheiro" | "Cartao" | "Boleto" | "Pix";
  days_ticket: string;
  freight: number;
  note_number: string;
  document_type: string;
  total: number;
  total_payed: number;
  issue_date: string;
  due_date: string | null;
  text_note: string | null;
  boleto_id?: string | null;
  source: "order";
};
